INSERT INTO `jalurpendaftaran` (`id_jalur`, `nama_jalur`, `jenjang`) VALUES
(1, 'Zonasi Kota', 'SMA'),
(2, 'Zonasi Kabupaten', 'SMA'),
(3, 'Afirmasi', 'SMA'),
(4, 'Prestasi Akademik', 'SMA'),
(5, 'Prestasi Non-Akademik', 'SMA'),
(6, 'Pindah Tugas Orang Tua', 'SMA'),
(7, 'Anak Guru', 'SMA'),
(8, 'Jalur Umum', 'SMA'),
(9, 'Jalur Khusus', 'SMA'),
(10, 'Jalur Mandiri', 'SMA'),
(11, 'Jalur Internasional', 'SMA'),
(12, 'Jalur Nasional', 'SMA'),
(13, 'Jalur Daerah', 'SMA'),
(14, 'Jalur Kejuaraan', 'SMA'),
(15, 'Jalur Beasiswa', 'SMA'),
(16, 'Jalur Kemitraan', 'SMA'),
(17, 'Jalur Tes Masuk', 'SMA'),
(18, 'Jalur PMDK', 'SMA'),
(19, 'Jalur RPL (Rekognisi Pembelajaran Lampau)', 'SMA'),
(20, 'Jalur Ekonomi Lemah', 'SMA'),
(21, 'Jalur Anak Berkebutuhan Khusus', 'SMA'),
(22, 'Jalur Bibit Unggul', 'SMA'),
(23, 'Jalur Siswa Berprestasi', 'SMA'),
(24, 'Jalur Siswa Berbakat', 'SMA'),
(25, 'Jalur Atlet', 'SMA'),
(26, 'Zonasi Kota', 'SMK'),
(27, 'Zonasi Kabupaten', 'SMK'),
(28, 'Afirmasi', 'SMK'),
(29, 'Prestasi Akademik', 'SMK'),
(30, 'Prestasi Non-Akademik', 'SMK'),
(31, 'Pindah Tugas Orang Tua', 'SMK'),
(32, 'Anak Guru', 'SMK'),
(33, 'Jalur Umum', 'SMK'),
(34, 'Jalur Khusus', 'SMK'),
(35, 'Jalur Mandiri', 'SMK'),
(36, 'Jalur Internasional', 'SMK'),
(37, 'Jalur Nasional', 'SMK'),
(38, 'Jalur Daerah', 'SMK'),
(39, 'Jalur Kejuaraan', 'SMK'),
(40, 'Jalur Beasiswa', 'SMK'),
(41, 'Jalur Kemitraan', 'SMK'),
(42, 'Jalur Tes Masuk', 'SMK'),
(43, 'Jalur PMDK', 'SMK'),
(44, 'Jalur RPL (Rekognisi Pembelajaran Lampau)', 'SMK'),
(45, 'Jalur Ekonomi Lemah', 'SMK'),
(46, 'Jalur Anak Berkebutuhan Khusus', 'SMK'),
(47, 'Jalur Bibit Unggul', 'SMK'),
(48, 'Jalur Siswa Berprestasi', 'SMK'),
(49, 'Jalur Siswa Berbakat', 'SMK'),
(50, 'Jalur Atlet', 'SMK');
