INSERT INTO sekolah (id_sekolah, nama_sekolah, alamat, jenjang) VALUES
(1, 'SMAN 1 Makassar', 'Jl. Baji Gau, Makassar', 'SMA'),
(2, 'SMAN 2 Makassar', 'Jl. Amanagappa, Makassar', 'SMA'),
(3, 'SMAN 3 Makassar', 'Jl. Gunung Batu Putih, Makassar', 'SMA'),
(4, 'SMAN 4 Makassar', 'Jl. Andi Pangeran Pettarani, Makassar', 'SMA'),
(5, 'SMAN 5 Makassar', 'Jl. Tupai, Makassar', 'SMA'),
(6, 'SMKN 1 Makassar', 'Jl. AP Pettarani, Makassar', 'SMK'),
(7, 'SMKN 2 Makassar', 'Jl. Monginsidi, Makassar', 'SMK'),
(8, 'SMKN 3 Makassar', 'Jl. Bandang, Makassar', 'SMK'),
(9, 'SMKN 4 Makassar', 'Jl. Dr. Wahidin Sudirohusodo, Makassar', 'SMK'),
(10, 'SMKN 5 Makassar', 'Jl. Sunu, Makassar', 'SMK'),
(11, 'SMAN 1 Gowa', 'Jl. Sultan Hasanuddin, Gowa', 'SMA'),
(12, 'SMAN 2 Gowa', 'Jl. Malino, Gowa', 'SMA'),
(13, 'SMAN 3 Gowa', 'Jl. Pallantikang, Gowa', 'SMA'),
(14, 'SMKN 1 Gowa', 'Jl. Malino, Gowa', 'SMK'),
(15, 'SMKN 2 Gowa', 'Jl. Limbung, Gowa', 'SMK'),
(16, 'SMAN 1 Maros', 'Jl. Nasrun Amrullah, Maros', 'SMA'),
(17, 'SMAN 2 Maros', 'Jl. Bontoa, Maros', 'SMA'),
(18, 'SMKN 1 Maros', 'Jl. Poros Maros, Maros', 'SMK'),
(19, 'SMKN 2 Maros', 'Jl. Tangkuru, Maros', 'SMK'),
(20, 'SMAN 1 Pangkep', 'Jl. Andi Mappe, Pangkep', 'SMA');
