INSERT INTO sekolah (id_sekolah, nama_sekolah, alamat, jenjang) VALUES
(1, 'SMAN 1 Makassar', 'Jl. Baji Gau, Makassar', 'SMA'),
(2, 'SMAN 2 Makassar', 'Jl. Amanagappa, Makassar', 'SMA'),
(3, 'SMAN 3 Makassar', 'Jl. Gunung Batu Putih, Makassar', 'SMA'),
(4, 'SMAN 4 Makassar', 'Jl. Andi Pangeran Pettarani, Makassar', 'SMA'),
(5, 'SMAN 5 Makassar', 'Jl. Tupai, Makassar', 'SMA'),
(6, 'SMAN 6 Makassar', 'Jl. Veteran Selatan, Makassar', 'SMA'),
(7, 'SMAN 7 Makassar', 'Jl. Cendrawasih, Makassar', 'SMA'),
(8, 'SMAN 8 Makassar', 'Jl. Sultan Alauddin, Makassar', 'SMA'),
(9, 'SMAN 9 Makassar', 'Jl. Rajawali, Makassar', 'SMA'),
(10, 'SMAN 10 Makassar', 'Jl. Urip Sumoharjo, Makassar', 'SMA'),
(11, 'SMKN 1 Makassar', 'Jl. AP Pettarani, Makassar', 'SMK'),
(12, 'SMKN 2 Makassar', 'Jl. Monginsidi, Makassar', 'SMK'),
(13, 'SMKN 3 Makassar', 'Jl. Bandang, Makassar', 'SMK'),
(14, 'SMKN 4 Makassar', 'Jl. Dr. Wahidin Sudirohusodo, Makassar', 'SMK'),
(15, 'SMKN 5 Makassar', 'Jl. Sunu, Makassar', 'SMK'),
(16, 'SMKN 6 Makassar', 'Jl. Sultan Hasanuddin, Makassar', 'SMK'),
(17, 'SMKN 7 Makassar', 'Jl. Jendral Sudirman, Makassar', 'SMK'),
(18, 'SMKN 8 Makassar', 'Jl. Perintis Kemerdekaan, Makassar', 'SMK'),
(19, 'SMKN 9 Makassar', 'Jl. Batua Raya, Makassar', 'SMK'),
(20, 'SMKN 10 Makassar', 'Jl. Hertasning, Makassar', 'SMK'),
(21, 'SMAN 1 Gowa', 'Jl. Sultan Hasanuddin, Gowa', 'SMA'),
(22, 'SMAN 2 Gowa', 'Jl. Malino, Gowa', 'SMA'),
(23, 'SMAN 3 Gowa', 'Jl. Pallantikang, Gowa', 'SMA'),
(24, 'SMAN 4 Gowa', 'Jl. Syekh Yusuf, Gowa', 'SMA'),
(25, 'SMAN 5 Gowa', 'Jl. Bontonompo, Gowa', 'SMA'),
(26, 'SMKN 1 Gowa', 'Jl. Malino, Gowa', 'SMK'),
(27, 'SMKN 2 Gowa', 'Jl. Limbung, Gowa', 'SMK'),
(28, 'SMKN 3 Gowa', 'Jl. Pallangga, Gowa', 'SMK'),
(29, 'SMAN 1 Maros', 'Jl. Nasrun Amrullah, Maros', 'SMA'),
(30, 'SMAN 2 Maros', 'Jl. Bontoa, Maros', 'SMA'),
(31, 'SMAN 3 Maros', 'Jl. Bantimurung, Maros', 'SMA'),
(32, 'SMKN 1 Maros', 'Jl. Poros Maros, Maros', 'SMK'),
(33, 'SMKN 2 Maros', 'Jl. Tangkuru, Maros', 'SMK'),
(34, 'SMAN 1 Pangkep', 'Jl. Andi Mappe, Pangkep', 'SMA'),
(35, 'SMAN 2 Pangkep', 'Jl. Soreang, Pangkep', 'SMA'),
(36, 'SMKN 1 Pangkep', 'Jl. Cendrawasih, Pangkep', 'SMK'),
(37, 'SMKN 2 Pangkep', 'Jl. Andi Mauraga, Pangkep', 'SMK'),
(38, 'SMAN 1 Takalar', 'Jl. Sudirman, Takalar', 'SMA'),
(39, 'SMAN 2 Takalar', 'Jl. H. Agus Salim, Takalar', 'SMA'),
(40, 'SMKN 1 Takalar', 'Jl. Pattallassang, Takalar', 'SMK'),
(41, 'SMKN 2 Takalar', 'Jl. Bontokassi, Takalar', 'SMK'),
(42, 'SMAN 1 Bone', 'Jl. Veteran, Bone', 'SMA'),
(43, 'SMAN 2 Bone', 'Jl. KH. Agus Salim, Bone', 'SMA'),
(44, 'SMKN 1 Bone', 'Jl. Andi Mappanyukki, Bone', 'SMK'),
(45, 'SMKN 2 Bone', 'Jl. Jendral Sudirman, Bone', 'SMK'),
(46, 'SMAN 1 Sinjai', 'Jl. Jenderal Sudirman, Sinjai', 'SMA'),
(47, 'SMAN 2 Sinjai', 'Jl. Persatuan Guru, Sinjai', 'SMA'),
(48, 'SMKN 1 Sinjai', 'Jl. Andi Sultan Daeng Radja, Sinjai', 'SMK'),
(49, 'SMKN 2 Sinjai', 'Jl. Poros Sinjai-Bulukumba, Sinjai', 'SMK'),
(50, 'SMKN 3 Sinjai', 'Jl. Poros Sinjai-Bulukumba, Sinjai', 'SMK');
