INSERT INTO `sekolah` (`nama_sekolah`, `alamat`, `jenjang`) VALUES
('SMAN 1 Makassar', 'Jl. Baji Gau, Makassar', 'SMA'),
('SMAN 2 Makassar', 'Jl. Amanagappa, Makassar', 'SMA'),
('SMAN 3 Makassar', 'Jl. Gunung Batu Putih, Makassar', 'SMA'),
('SMAN 4 Makassar', 'Jl. Andi Pangeran Pettarani, Makassar', 'SMA'),
('SMAN 5 Makassar', 'Jl. Tupai, Makassar', 'SMA'),
('SMAN 6 Makassar', 'Jl. Veteran Selatan, Makassar', 'SMA'),
('SMAN 7 Makassar', 'Jl. Cendrawasih, Makassar', 'SMA'),
('SMAN 8 Makassar', 'Jl. Sultan Alauddin, Makassar', 'SMA'),
('SMAN 9 Makassar', 'Jl. Rajawali, Makassar', 'SMA'),
('SMAN 10 Makassar', 'Jl. Urip Sumoharjo, Makassar', 'SMA'),
('SMKN 1 Makassar', 'Jl. AP Pettarani, Makassar', 'SMK'),
('SMKN 2 Makassar', 'Jl. Monginsidi, Makassar', 'SMK'),
('SMKN 3 Makassar', 'Jl. Bandang, Makassar', 'SMK'),
('SMKN 4 Makassar', 'Jl. Dr. Wahidin Sudirohusodo, Makassar', 'SMK'),
('SMKN 5 Makassar', 'Jl. Sunu, Makassar', 'SMK'),
('SMKN 6 Makassar', 'Jl. Sultan Hasanuddin, Makassar', 'SMK'),
('SMKN 7 Makassar', 'Jl. Jendral Sudirman, Makassar', 'SMK'),
('SMKN 8 Makassar', 'Jl. Perintis Kemerdekaan, Makassar', 'SMK'),
('SMKN 9 Makassar', 'Jl. Batua Raya, Makassar', 'SMK'),
('SMKN 10 Makassar', 'Jl. Hertasning, Makassar', 'SMK'),
('SMAN 1 Gowa', 'Jl. Sultan Hasanuddin, Gowa', 'SMA'),
('SMAN 2 Gowa', 'Jl. Malino, Gowa', 'SMA'),
('SMAN 3 Gowa', 'Jl. Pallantikang, Gowa', 'SMA'),
('SMAN 4 Gowa', 'Jl. Syekh Yusuf, Gowa', 'SMA'),
('SMAN 5 Gowa', 'Jl. Bontonompo, Gowa', 'SMA'),
('SMKN 1 Gowa', 'Jl. Malino, Gowa', 'SMK'),
('SMKN 2 Gowa', 'Jl. Limbung, Gowa', 'SMK'),
('SMKN 3 Gowa', 'Jl. Pallangga, Gowa', 'SMK'),
('SMAN 1 Maros', 'Jl. Nasrun Amrullah, Maros', 'SMA'),
('SMAN 2 Maros', 'Jl. Bontoa, Maros', 'SMA'),
('SMAN 3 Maros', 'Jl. Bantimurung, Maros', 'SMA'),
('SMKN 1 Maros', 'Jl. Poros Maros, Maros', 'SMK'),
('SMKN 2 Maros', 'Jl. Tangkuru, Maros', 'SMK'),
('SMAN 1 Pangkep', 'Jl. Andi Mappe, Pangkep', 'SMA'),
('SMAN 2 Pangkep', 'Jl. Soreang, Pangkep', 'SMA'),
('SMKN 1 Pangkep', 'Jl. Cendrawasih, Pangkep', 'SMK'),
('SMKN 2 Pangkep', 'Jl. Andi Mauraga, Pangkep', 'SMK'),
('SMAN 1 Takalar', 'Jl. Sudirman, Takalar', 'SMA'),
('SMAN 2 Takalar', 'Jl. H. Agus Salim, Takalar', 'SMA'),
('SMKN 1 Takalar', 'Jl. Pattallassang, Takalar', 'SMK'),
('SMKN 2 Takalar', 'Jl. Bontokassi, Takalar', 'SMK'),
('SMAN 1 Bone', 'Jl. Veteran, Bone', 'SMA'),
('SMAN 2 Bone', 'Jl. KH. Agus Salim, Bone', 'SMA'),
('SMKN 1 Bone', 'Jl. Andi Mappanyukki, Bone', 'SMK'),
('SMKN 2 Bone', 'Jl. Jendral Sudirman, Bone', 'SMK'),
('SMAN 1 Sinjai', 'Jl. Jenderal Sudirman, Sinjai', 'SMA'),
('SMAN 2 Sinjai', 'Jl. Persatuan Guru, Sinjai', 'SMA'),
('SMKN 1 Sinjai', 'Jl. Andi Sultan Daeng Radja, Sinjai', 'SMK'),
('SMKN 2 Sinjai', 'Jl. Poros Sinjai-Bulukumba, Sinjai', 'SMK');
('SMKN 3 Sinjai', 'Jl. Poros Sinjai-Bulukumba, Sinjai', 'SMK');
